my_packages <- c("readr","tidyverse", "lubridate","ggplot2","ggpubr","dplyr","knitr"
                 ,"rmarkdown","qwraps2","roxygen2")

package.check <-  lapply(
  my_packages,
  FUN = function(x) {
    if (!require(x, character.only = TRUE)) {
      install.packages(x, dependencies = TRUE)
      library(x, character.only = TRUE)
    }
  }
)

sepsis_adult <- read_csv("2022.QTR1.NYSDOH_Sepsis_Adult_D3.0.csv",
                         col_types = ( cols(
                           arrival_dt = col_datetime(format = "%Y-%m-%d %H:%M"),
                           admission_dt = col_datetime(format = "%Y-%m-%d %H:%M"),
                           date_of_birth = col_datetime(format = "%Y-%m-%d"),
                           discharge_dt = col_datetime(format = "%Y-%m-%d %H:%M"),
                           discharge_status = col_double(),
                           ethnicity = col_character(),
                           facility_identifier = col_character(), 
                           gender = col_factor(levels = c("M", "F")), 
                           icd_10_cm_code_1 = col_character(),
                           icd_10_cm_code_2 = col_character(),
                           icd_10_cm_code_3 = col_character(),
                           icd_10_cm_code_4 = col_character(),
                           icd_10_cm_code_5 = col_character(),
                           icd_10_cm_code_6 = col_character(),
                           icd_10_cm_code_7 = col_character(),
                           icd_10_cm_code_8 = col_character(),
                           icd_10_cm_code_9 = col_character(),
                           icd_10_cm_code_10 = col_character(),
                           icd_10_cm_code_11 = col_character(),
                           icd_10_cm_code_12 = col_character(),
                           icd_10_cm_code_13 = col_character(),
                           icd_10_cm_code_14 = col_character(),
                           icd_10_cm_code_15 = col_character(),
                           icd_10_cm_code_16 = col_character(),
                           icd_10_cm_code_17 = col_character(),
                           icd_10_cm_code_18 = col_character(),
                           icd_10_cm_code_19 = col_character(),
                           icd_10_cm_code_20 = col_character(),
                           icd_10_cm_code_21 = col_character(),
                           icd_10_cm_code_22 = col_character(),
                           icd_10_cm_code_23 = col_character(),
                           icd_10_cm_code_24 = col_character(),
                           icd_10_cm_code_25 = col_character(),
                           icd_10_cm_poa_indicator_1 = col_factor(levels = c("Y", "N", "U", "E", "W", "1")), 
                           icd_10_cm_poa_indicator_2 = col_factor(levels = c("Y", "N", "U", "E", "W", "1")), 
                           icd_10_cm_poa_indicator_3 = col_factor(levels = c("Y", "N", "U", "E", "W", "1")), 
                           icd_10_cm_poa_indicator_4 = col_factor(levels = c("Y", "N", "U", "E", "W", "1")), 
                           icd_10_cm_poa_indicator_5 = col_factor(levels = c("Y", "N", "U", "E", "W", "1")), 
                           icd_10_cm_poa_indicator_6 = col_factor(levels = c("Y", "N", "U", "E", "W", "1")), 
                           icd_10_cm_poa_indicator_7 = col_factor(levels = c("Y", "N", "U", "E", "W", "1")), 
                           icd_10_cm_poa_indicator_8 = col_factor(levels = c("Y", "N", "U", "E", "W", "1")), 
                           icd_10_cm_poa_indicator_9 = col_factor(levels = c("Y", "N", "U", "E", "W", "1")), 
                           icd_10_cm_poa_indicator_10 = col_factor(levels = c("Y", "N", "U", "E", "W", "1")), 
                           icd_10_cm_poa_indicator_11 = col_factor(levels = c("Y", "N", "U", "E", "W", "1")), 
                           icd_10_cm_poa_indicator_12 = col_factor(levels = c("Y", "N", "U", "E", "W", "1")), 
                           icd_10_cm_poa_indicator_13 = col_factor(levels = c("Y", "N", "U", "E", "W", "1")), 
                           icd_10_cm_poa_indicator_14 = col_factor(levels = c("Y", "N", "U", "E", "W", "1")), 
                           icd_10_cm_poa_indicator_15 = col_factor(levels = c("Y", "N", "U", "E", "W", "1")), 
                           icd_10_cm_poa_indicator_16 = col_factor(levels = c("Y", "N", "U", "E", "W", "1")), 
                           icd_10_cm_poa_indicator_17 = col_factor(levels = c("Y", "N", "U", "E", "W", "1")), 
                           icd_10_cm_poa_indicator_18 = col_factor(levels = c("Y", "N", "U", "E", "W", "1")), 
                           icd_10_cm_poa_indicator_19 = col_factor(levels = c("Y", "N", "U", "E", "W", "1")), 
                           icd_10_cm_poa_indicator_20 = col_factor(levels = c("Y", "N", "U", "E", "W", "1")), 
                           icd_10_cm_poa_indicator_21 = col_factor(levels = c("Y", "N", "U", "E", "W", "1")), 
                           icd_10_cm_poa_indicator_22 = col_factor(levels = c("Y", "N", "U", "E", "W", "1")), 
                           icd_10_cm_poa_indicator_23 = col_factor(levels = c("Y", "N", "U", "E", "W", "1")), 
                           icd_10_cm_poa_indicator_24 = col_factor(levels = c("Y", "N", "U", "E", "W", "1")), 
                           icd_10_cm_poa_indicator_25 = col_factor(levels = c("Y", "N", "U", "E", "W", "1")), 
                           inclusion_septic_shock = col_factor(levels = c("0", "1")),
                           inclusion_severe_covid = col_factor(levels = c("0", "1")),
                           inclusion_severe_sepsis = col_factor(levels = c("0", "1")),
                           insurance_number = col_character(),
                           medical_record_number = col_double(),
                           other_payer = col_character(),
                           patient_control_number = col_double(),
                           pat_addr_city = col_character(),
                           pat_addr_cnty_cd = col_double(),
                           pat_addr_line1 = col_character(),
                           pat_addr_line2 = col_character(),
                           pat_addr_st = col_character(),
                           patient_zip_code_of_residence = col_character(),
                           payer = col_character(),
                           race = col_character(),
                           source_of_admission = col_double(),
                           transferred_in = col_factor(levels = c("0", "1")),
                           transferred_out = col_factor(levels = c("0", "1")),
                           transfer_facility_id_receiving = col_double(),
                           transfer_facility_id_sending = col_double(),
                           transfer_facility_nm_receiving = col_character(),
                           transfer_facility_nm_sending = col_character(),
                           unique_personal_identifier = col_character(),
                           acute_cardiovascular_conditions_poa = col_factor(levels = c("0", "1","2","3","1:02","1:02:03","2:03")),
                           aids_hiv_disease = col_factor(levels = c("0", "1")),
                           asthma = col_factor(levels = c("0", "1")),
                           chronic_liver_disease = col_factor(levels = c("0", "1")),
                           chronic_kidney_disease = col_factor(levels = c("0", "1")),
                           chronic_respiratory_failure = col_factor(levels = c("0", "1")),
                           coagulopathy_poa = col_factor(levels = c("0", "1")),
                           congestive_heart_failure = col_factor(levels = c("0", "1")),
                           copd = col_factor(levels = c("0", "1")),
                           dementia = col_factor(levels = c("0", "1")),
                           diabetes = col_factor(levels = c("0", "1")),
                           dialysis_comorbidity_poa = col_factor(levels = c("0", "1")),
                           history_of_covid = col_factor(levels = c("0", "1")),
                           history_of_covid_dt = col_datetime(format = "%Y-%m-%d %H:%M"),
                           history_of_other_cvd = col_factor(levels = c("0", "1","2","3","4","5","1:02","1:03","1:04","1:05","2:03","2:04"
                                                                        ,"2:05","3:04","3:05","4:05","1:02:03","1:02:04","1:02:05"
                                                                        ,"1:03:04","1:03:05","1:04:05","2:03:04","2:03:05","3:04:05")),
                           hypertension = col_factor(levels = c("0", "1")),
                           immunocompromising = col_factor(levels = c("0", "1")),
                           lymphoma_leukemia_multi_myeloma = col_factor(levels = c("0", "1")),
                           mechanical_vent_comorbidity_poa = col_factor(levels = c("0", "1")),
                           medication_immune_modifying_pre_hospital = col_factor(levels = c("0", "1")),
                           metastatic_cancer = col_factor(levels = c("0", "1")),
                           obesity = col_factor(levels = c("0", "1")),
                           patient_care_considerations = col_factor(levels = c("0", "1","2","1:02")),
                           patient_care_considerations_date = col_datetime(format = "%Y-%m-%d"),
                           pregnancy_comorbidity = col_factor(levels = c("0", "1")),
                           pregnancy_status = col_factor(levels = c("0", "1")),
                           skin_disorders_burns = col_factor(levels = c("0", "1","2","3","1:02","1:03","2:03")),
                           smoking_vaping = col_factor(levels = c("0", "1")),
                           tracheostomy_on_arrival_poa = col_factor(levels = c("0", "1")),
                           covid_exposure = col_factor(levels = c("0", "1")),
                           covid_virus = col_factor(levels = c("0", "1")),
                           drug_resistant_pathogen = col_factor(levels = c("0", "1")),
                           flu_positive = col_factor(levels = c("0", "1")),
                           suspected_source_of_infection = col_character(),
                           dialysis_treatment = col_factor(levels = c("0", "1")),
                           during_hospital_immune_mod_med = col_factor(levels = c("0", "1")),
                           during_hospital_remdesivir = col_factor(levels = c("0", "1")),
                           ecmo = col_factor(levels = c("0", "1")),
                           high_flow_nasal_cannula = col_factor(levels = c("0", "1")),
                           mechanical_vent_treatment = col_factor(levels = c("0", "1")),
                           non_invasive_pos_pressure_vent = col_factor(levels = c("0", "1")),
                           vasopressor_administration = col_factor(levels = c("0", "1")),
                           dialysis_outcome = col_factor(levels = c("0", "1")),
                           mechanical_vent_outcome = col_factor(levels = c("0", "1")),
                           tracheostomy_at_discharge = col_factor(levels = c("0", "1")),
                           cv_outcomes_in_hospital = col_factor(levels = c("0", "1","2","3","4","1:02","1:03","1:04","2:03","2:04","3:04"
                                                                           ,"1:02:03","1:02:04","1:03:04")),
                           icu_during_hospitalization = col_factor(levels = c("0", "1")),
                           tracheostomy_in_hospital = col_factor(levels = c("0", "1")),
                           aptt_1 = col_double(),
                           aptt_2 = col_double(),
                           aptt_3 = col_double(),
                           aptt_max = col_double(),
                           aptt_dt_1 = col_datetime(format = "%Y-%m-%d %H:%M"),
                           aptt_dt_2 = col_datetime(format = "%Y-%m-%d %H:%M"),
                           aptt_dt_3 = col_datetime(format = "%Y-%m-%d %H:%M"),
                           aptt_dt_max = col_datetime(format = "%Y-%m-%d %H:%M"),
                           bilirubin_arrival = col_double(),
                           bilirubin_max = col_double(),
                           bilirubin_arrival_dt = col_datetime(format = "%Y-%m-%d %H:%M"),
                           bilirubin_max_dt = col_datetime(format = "%Y-%m-%d %H:%M"),
                           creatinine_arrival = col_double(),
                           creatinine_max = col_double(),
                           creatinine_arrival_dt = col_datetime(format = "%Y-%m-%d %H:%M"),
                           creatinine_max_dt = col_datetime(format = "%Y-%m-%d %H:%M"),
                           diastolic_1 = col_double(),
                           diastolic_2 = col_double(),
                           diastolic_3 = col_double(),
                           diastolic_min = col_double(),
                           diastolic_dt_1 = col_datetime(format = "%Y-%m-%d %H:%M"),
                           diastolic_dt_2 = col_datetime(format = "%Y-%m-%d %H:%M"),
                           diastolic_dt_3 = col_datetime(format = "%Y-%m-%d %H:%M"),
                           diastolic_dt_min = col_datetime(format = "%Y-%m-%d %H:%M"),
                           inr_1 = col_double(),
                           inr_2 = col_double(),
                           inr_3 = col_double(),
                           inr_max = col_double(),
                           inr_dt_1 = col_datetime(format = "%Y-%m-%d %H:%M"),
                           inr_dt_2 = col_datetime(format = "%Y-%m-%d %H:%M"),
                           inr_dt_3 = col_datetime(format = "%Y-%m-%d %H:%M"),
                           inr_dt_max = col_datetime(format = "%Y-%m-%d %H:%M"),
                           lactate_level_1 = col_double(),
                           lactate_level_2 = col_double(),
                           lactate_level_3 = col_double(),
                           lactate_level_max = col_double(),
                           lactate_level_dt_1 = col_datetime(format = "%Y-%m-%d %H:%M"),
                           lactate_level_dt_2 = col_datetime(format = "%Y-%m-%d %H:%M"),
                           lactate_level_dt_3 = col_datetime(format = "%Y-%m-%d %H:%M"),
                           lactate_level_dt_max = col_datetime(format = "%Y-%m-%d %H:%M"),
                           organ_dysfunc_cardiovascular = col_factor(levels = c("0", "1")),
                           organ_dysfunc_cns = col_factor(levels = c("0", "1")),
                           organ_dysfunc_hematologic = col_factor(levels = c("0", "1")),
                           organ_dysfunc_hepatic = col_factor(levels = c("0", "1")),
                           organ_dysfunc_renal = col_factor(levels = c("0", "1")),
                           organ_dysfunc_respiratory = col_factor(levels = c("0", "1")),
                           platelets_1 = col_double(),
                           platelets_2 = col_double(),
                           platelets_3 = col_double(),
                           platelets_min = col_double(),
                           platelets_dt_1 = col_datetime(format = "%Y-%m-%d %H:%M"),
                           platelets_dt_2 = col_datetime(format = "%Y-%m-%d %H:%M"),
                           platelets_dt_3 = col_datetime(format = "%Y-%m-%d %H:%M"),
                           platelets_dt_min = col_datetime(format = "%Y-%m-%d %H:%M"),
                           sirs_heartrate_1 = col_double(),
                           sirs_heartrate_2 = col_double(),
                           sirs_heartrate_3 = col_double(),
                           sirs_heartrate_max = col_double(),
                           sirs_heartrate_dt_1 = col_datetime(format = "%Y-%m-%d %H:%M"),
                           sirs_heartrate_dt_2 = col_datetime(format = "%Y-%m-%d %H:%M"),
                           sirs_heartrate_dt_3 = col_datetime(format = "%Y-%m-%d %H:%M"),
                           sirs_heartrate_dt_max = col_datetime(format = "%Y-%m-%d %H:%M"),
                           sirs_leukocyte_arrival = col_double(),
                           sirs_leukocyte_min = col_double(),
                           sirs_leukocyte_max = col_double(),
                           sirs_leukocyte_arrival_dt = col_datetime(format = "%Y-%m-%d %H:%M"),
                           sirs_leukocyte_min_dt = col_datetime(format = "%Y-%m-%d %H:%M"),
                           sirs_leukocyte_max_dt = col_datetime(format = "%Y-%m-%d %H:%M"),
                           sirs_respiratoryrate_1 = col_double(),
                           sirs_respiratoryrate_2 = col_double(),
                           sirs_respiratoryrate_3 = col_double(),
                           sirs_respiratoryrate_max = col_double(),
                           sirs_respiratoryrate_dt_1 = col_datetime(format = "%Y-%m-%d %H:%M"),
                           sirs_respiratoryrate_dt_2 = col_datetime(format = "%Y-%m-%d %H:%M"),
                           sirs_respiratoryrate_dt_3 = col_datetime(format = "%Y-%m-%d %H:%M"),
                           sirs_respiratoryrate_dt_max = col_datetime(format = "%Y-%m-%d %H:%M"),
                           sirs_temperature_1 = col_double(),
                           sirs_temperature_2 = col_double(),
                           sirs_temperature_3 = col_double(),
                           sirs_temperature_max = col_double(),
                           sirs_temperature_dt_1 = col_datetime(format = "%Y-%m-%d %H:%M"),
                           sirs_temperature_dt_2 = col_datetime(format = "%Y-%m-%d %H:%M"),
                           sirs_temperature_dt_3 = col_datetime(format = "%Y-%m-%d %H:%M"),
                           sirs_temperature_dt_max = col_datetime(format = "%Y-%m-%d %H:%M"),
                           systolic_1 = col_double(),
                           systolic_2 = col_double(),
                           systolic_3 = col_double(),
                           systolic_min = col_double(),
                           systolic_dt_1 = col_datetime(format = "%Y-%m-%d %H:%M"),
                           systolic_dt_2 = col_datetime(format = "%Y-%m-%d %H:%M"),
                           systolic_dt_3 = col_datetime(format = "%Y-%m-%d %H:%M"),
                           systolic_dt_min = col_datetime(format = "%Y-%m-%d %H:%M"),
                         ))
                         )

sepsis_pediatrics <- readr::read_csv("2022.QTR1.NYSDOH_Sepsis_PEDs_D2.0.csv",
                                     col_types = cols(
                                       arrival_dt = col_datetime(format = "%Y-%m-%d %H:%M"),
                                       admission_dt = col_datetime(format = "%Y-%m-%d %H:%M"),
                                       date_of_birth = col_datetime(format = "%Y-%m-%d"),
                                       discharge_dt = col_datetime(format = "%Y-%m-%d %H:%M"),
                                       discharge_status = col_character(),
                                       ethnicity = col_character(),
                                       facility_identifier = col_character(),
                                       gender = col_factor(levels = c("M", "F")),
                                       icd_10_cm_code_1 = col_character(),
                                       icd_10_cm_code_2 = col_character(),
                                       icd_10_cm_code_3 = col_character(),
                                       icd_10_cm_code_4 = col_character(),
                                       icd_10_cm_code_5 = col_character(),
                                       icd_10_cm_code_6 = col_character(),
                                       icd_10_cm_code_7 = col_character(),
                                       icd_10_cm_code_8 = col_character(),
                                       icd_10_cm_code_9 = col_character(),
                                       icd_10_cm_code_10 = col_character(),
                                       icd_10_cm_code_11 = col_character(),
                                       icd_10_cm_code_12 = col_character(),
                                       icd_10_cm_code_13 = col_character(),
                                       icd_10_cm_code_14 = col_character(),
                                       icd_10_cm_code_15 = col_character(),
                                       icd_10_cm_code_16 = col_character(),
                                       icd_10_cm_code_17 = col_character(),
                                       icd_10_cm_code_18 = col_character(),
                                       icd_10_cm_code_19 = col_character(),
                                       icd_10_cm_code_20 = col_character(),
                                       icd_10_cm_code_21 = col_character(),
                                       icd_10_cm_code_22 = col_character(),
                                       icd_10_cm_code_23 = col_character(),
                                       icd_10_cm_code_24 = col_character(),
                                       icd_10_cm_code_25 = col_character(),
                                       icd_10_cm_poa_indicator_1 = col_character(),
                                       icd_10_cm_poa_indicator_2 = col_character(),
                                       icd_10_cm_poa_indicator_3 = col_character(),
                                       icd_10_cm_poa_indicator_4 = col_character(),
                                       icd_10_cm_poa_indicator_5 = col_character(),
                                       icd_10_cm_poa_indicator_6 = col_character(),
                                       icd_10_cm_poa_indicator_7 = col_character(),
                                       icd_10_cm_poa_indicator_8 = col_character(),
                                       icd_10_cm_poa_indicator_9 = col_character(),
                                       icd_10_cm_poa_indicator_10 = col_character(),
                                       icd_10_cm_poa_indicator_11 = col_character(),
                                       icd_10_cm_poa_indicator_12 = col_character(),
                                       icd_10_cm_poa_indicator_13 = col_character(),
                                       icd_10_cm_poa_indicator_14 = col_character(),
                                       icd_10_cm_poa_indicator_15 = col_character(),
                                       icd_10_cm_poa_indicator_16 = col_character(),
                                       icd_10_cm_poa_indicator_17 = col_character(),
                                       icd_10_cm_poa_indicator_18 = col_character(),
                                       icd_10_cm_poa_indicator_19 = col_character(),
                                       icd_10_cm_poa_indicator_20 = col_character(),
                                       icd_10_cm_poa_indicator_21 = col_character(),
                                       icd_10_cm_poa_indicator_22 = col_character(),
                                       icd_10_cm_poa_indicator_23 = col_character(),
                                       icd_10_cm_poa_indicator_24 = col_character(),
                                       icd_10_cm_poa_indicator_25 = col_character(),
                                       inclusion_covid_19 = col_factor(levels = c("0", "1")),
                                       inclusion_septic_shock = col_factor(levels = c("0", "1")),
                                       inclusion_severe_sepsis = col_factor(levels = c("0", "1")),
                                       insurance_number = col_character(),
                                       medical_record_number = col_double(),
                                       other_payer = col_character(),
                                       patient_control_number = col_double(),
                                       pat_addr_city = col_character(),
                                       pat_addr_cnty_cd = col_character(),
                                       pat_addr_line1 = col_character(),
                                       pat_addr_line2 = col_character(),
                                       pat_addr_st = col_character(),
                                       patient_zip_code_of_residence = col_character(),
                                       payer = col_character(),
                                       race = col_character(),
                                       source_of_admission = col_double(),
                                       transferred_in = col_factor(levels = c("0", "1")),
                                       transferred_out = col_factor(levels = c("0", "1")),
                                       transfer_facility_id_receiving = col_character(),
                                       transfer_facility_id_sending = col_character(),
                                       transfer_facility_nm_receiving = col_character(),
                                       transfer_facility_nm_sending = col_character(),
                                       unique_personal_identifier = col_character(),
                                       acute_cardiovascular_conditions_poa = col_factor(levels = c("0", "1","2","3","4","1:02","1:03"
                                                                                                   ,"1:04","2:03","2:04","3:04")),
                                       acquired_absent_spleen = col_factor(levels = c("0", "1")),
                                       adrenal_gland_disorder_poa = col_factor(levels = c("0", "1")),
                                       aids_hiv_disease = col_factor(levels = c("0", "1")),
                                       asthma = col_factor(levels = c("0", "1")),
                                       bronchopulmonary_dysplasia = col_factor(levels = c("0", "1")),
                                       chronic_liver_disease = col_factor(levels = c("0", "1")),
                                       chronic_kidney_disease = col_factor(levels = c("0", "1")),
                                       chronic_respiratory_failure = col_factor(levels = c("0", "1")),
                                       coagulopathy_poa = col_factor(levels = c("0", "1")),
                                       congestive_heart_failure = col_factor(levels = c("0", "1")),
                                       cystic_fibrosis = col_factor(levels = c("0", "1")),
                                       diabetes = col_factor(levels = c("0", "1")),
                                       dialysis_comorbidity_poa = col_factor(levels = c("0", "1")),
                                       history_of_covid = col_factor(levels = c("0", "1")),
                                       history_of_covid_dt = col_datetime(format = "%Y-%m-%d %H:%M"),
                                       history_of_other_cvd = col_character(),
                                       hypertension = col_factor(levels = c("0", "1")),
                                       immunocompromising = col_factor(levels = c("0", "1")),
                                       kawasaki_mucocutaneous = col_factor(levels = c("0", "1")),
                                       lymphoma_leukemia_multi_myeloma = col_factor(levels = c("0", "1")),
                                       mechanical_vent_comorbidity_poa = col_factor(levels = c("0", "1")),
                                       medication_immune_modifying_pre_hospital = col_factor(levels = c("0", "1")),
                                       metastatic_cancer = col_factor(levels = c("0", "1")),
                                       neutropenic_patients_poa = col_factor(levels = c("0", "1")),
                                       obesity = col_factor(levels = c("0", "1")),
                                       patient_care_considerations = col_factor(levels = c("0", "1","2","1:2")),
                                       patient_care_considerations_date = col_date(format = "%Y-%m-%d"),
                                       pregnancy_comorbidity = col_factor(levels = c("0", "1")),
                                       pregnancy_status = col_factor(levels = c("0", "1")),
                                       prematurity = col_factor(levels = c("0", "1","2")),
                                       sickle_cell_disease = col_factor(levels = c("0", "1")),
                                       skin_disorders_burns = col_factor(levels = c("0", "1","2","3","1:02","1:03","2:03")),
                                       smoking_vaping = col_factor(levels = c("0", "1")),
                                       stem_cell_transplant_recipients = col_factor(levels = c("0", "1")),
                                       covid_exposure = col_factor(levels = c("0", "1")),
                                       covid_virus = col_factor(levels = c("0", "1")),
                                       drug_resistant_pathogen = col_factor(levels = c("0", "1")),
                                       flu_positive = col_factor(levels = c("0", "1")),
                                       suspected_source_of_infection = col_character(),
                                       dialysis_treatment = col_factor(levels = c("0", "1")),
                                       during_hospital_immune_mod_med = col_factor(levels = c("0", "1")),
                                       during_hospital_remdesivir = col_factor(levels = c("0", "1")),
                                       ecmo = col_factor(levels = c("0", "1")),
                                       high_flow_nasal_cannula = col_factor(levels = c("0", "1")),
                                       ivig = col_factor(levels = c("0", "1")),
                                       mechanical_vent_treatment = col_double(),
                                       non_invasive_pos_pressure_vent = col_factor(levels = c("0", "1")),
                                       vasopressor_administration = col_factor(levels = c("0", "1")),
                                       dialysis_outcome = col_factor(levels = c("0", "1")),
                                       mechanical_vent_outcome = col_factor(levels = c("0", "1")),
                                       neurological_outcome = col_factor(levels = c("0", "1")),
                                       cv_outcomes_in_hospital = col_factor(levels = c("0", "1","2","3","4","1:02","1:03","1:04","2:03"
                                                                                       ,"2:04","3:04")),
                                       icu_during_hospitalization = col_factor(levels = c("0", "1")),
                                       aptt_1 = col_double(),
                                       aptt_2 = col_double(),
                                       aptt_3 = col_double(),
                                       aptt_max = col_double(),
                                       aptt_dt_1 = col_datetime(format = "%Y-%m-%d %H:%M"),
                                       aptt_dt_2 = col_datetime(format = "%Y-%m-%d %H:%M"),
                                       aptt_dt_3 = col_datetime(format = "%Y-%m-%d %H:%M"),
                                       aptt_dt_max = col_datetime(format = "%Y-%m-%d %H:%M"),
                                       bilirubin_arrival = col_double(),
                                       bilirubin_max = col_double(),
                                       bilirubin_arrival_dt = col_datetime(format = "%Y-%m-%d %H:%M"),
                                       bilirubin_max_dt = col_datetime(format = "%Y-%m-%d %H:%M"),
                                       creatinine_arrival = col_double(),
                                       creatinine_max = col_double(),
                                       creatinine_arrival_dt = col_datetime(format = "%Y-%m-%d %H:%M"),
                                       creatinine_max_dt = col_datetime(format = "%Y-%m-%d %H:%M"),
                                       diastolic_1 = col_double(),
                                       diastolic_2 = col_double(),
                                       diastolic_3 = col_double(),
                                       diastolic_min = col_double(),
                                       diastolic_dt_1 = col_datetime(format = "%Y-%m-%d %H:%M"),
                                       diastolic_dt_2 = col_datetime(format = "%Y-%m-%d %H:%M"),
                                       diastolic_dt_3 = col_datetime(format = "%Y-%m-%d %H:%M"),
                                       diastolic_dt_min = col_datetime(format = "%Y-%m-%d %H:%M"),
                                       inr_1 = col_double(),
                                       inr_2 = col_double(),
                                       inr_3 = col_double(),
                                       inr_max = col_double(),
                                       inr_dt_1 = col_datetime(format = "%Y-%m-%d %H:%M"),
                                       inr_dt_2 = col_datetime(format = "%Y-%m-%d %H:%M"),
                                       inr_dt_3 = col_datetime(format = "%Y-%m-%d %H:%M"),
                                       inr_dt_max = col_datetime(format = "%Y-%m-%d %H:%M"),
                                       lactate_level_1 = col_double(),
                                       lactate_level_2 = col_double(),
                                       lactate_level_3 = col_double(),
                                       lactate_level_max = col_double(),
                                       lactate_level_dt_1 = col_datetime(format = "%Y-%m-%d %H:%M"),
                                       lactate_level_dt_2 = col_datetime(format = "%Y-%m-%d %H:%M"),
                                       lactate_level_dt_3 = col_datetime(format = "%Y-%m-%d %H:%M"),
                                       lactate_level_dt_max = col_datetime(format = "%Y-%m-%d %H:%M"),
                                       organ_dysfunc_cardiovascular = col_factor(levels = c("0", "1")),
                                       organ_dysfunc_cns = col_factor(levels = c("0", "1")),
                                       organ_dysfunc_hematologic = col_factor(levels = c("0", "1")),
                                       organ_dysfunc_hepatic = col_factor(levels = c("0", "1")),
                                       organ_dysfunc_renal = col_factor(levels = c("0", "1")),
                                       organ_dysfunc_respiratory = col_factor(levels = c("0", "1")),
                                       platelets_1 = col_double(),
                                       platelets_2 = col_double(),
                                       platelets_3 = col_double(),
                                       platelets_min = col_double(),
                                       platelets_dt_1 = col_datetime(format = "%Y-%m-%d %H:%M"),
                                       platelets_dt_2 = col_datetime(format = "%Y-%m-%d %H:%M"),
                                       platelets_dt_3 = col_datetime(format = "%Y-%m-%d %H:%M"),
                                       platelets_dt_min = col_datetime(format = "%Y-%m-%d %H:%M"),
                                       sirs_heartrate_1 = col_double(),
                                       sirs_heartrate_2 = col_double(),
                                       sirs_heartrate_3 = col_double(),
                                       sirs_heartrate_max = col_double(),
                                       sirs_heartrate_dt_1 = col_datetime(format = "%Y-%m-%d %H:%M"),
                                       sirs_heartrate_dt_2 = col_datetime(format = "%Y-%m-%d %H:%M"),
                                       sirs_heartrate_dt_3 = col_datetime(format = "%Y-%m-%d %H:%M"),
                                       sirs_heartrate_dt_max = col_datetime(format = "%Y-%m-%d %H:%M"),
                                       sirs_leukocyte_arrival = col_double(),
                                       sirs_leukocyte_min = col_double(),
                                       sirs_leukocyte_max = col_double(),
                                       sirs_leukocyte_arrival_dt = col_datetime(format = "%Y-%m-%d %H:%M"),
                                       sirs_leukocyte_min_dt = col_datetime(format = "%Y-%m-%d %H:%M"),
                                       sirs_leukocyte_max_dt = col_datetime(format = "%Y-%m-%d %H:%M"),
                                       sirs_respiratoryrate_1 = col_double(),
                                       sirs_respiratoryrate_2 = col_double(),
                                       sirs_respiratoryrate_3 = col_double(),
                                       sirs_respiratoryrate_max = col_double(),
                                       sirs_respiratoryrate_dt_1 = col_datetime(format = "%Y-%m-%d %H:%M"),
                                       sirs_respiratoryrate_dt_2 = col_datetime(format = "%Y-%m-%d %H:%M"),
                                       sirs_respiratoryrate_dt_3 = col_datetime(format = "%Y-%m-%d %H:%M"),
                                       sirs_respiratoryrate_dt_max = col_datetime(format = "%Y-%m-%d %H:%M"),
                                       sirs_temperature_1 = col_double(),
                                       sirs_temperature_2 = col_double(),
                                       sirs_temperature_3 = col_double(),
                                       sirs_temperature_max = col_double(),
                                       sirs_temperature_dt_1 = col_datetime(format = "%Y-%m-%d %H:%M"),
                                       sirs_temperature_dt_2 = col_datetime(format = "%Y-%m-%d %H:%M"),
                                       sirs_temperature_dt_3 = col_datetime(format = "%Y-%m-%d %H:%M"),
                                       sirs_temperature_dt_max = col_datetime(format = "%Y-%m-%d %H:%M"),
                                       systolic_1 = col_double(),
                                       systolic_2 = col_double(),
                                       systolic_3 = col_double(),
                                       systolic_min = col_double(),
                                       systolic_dt_1 = col_datetime(format = "%Y-%m-%d %H:%M"),
                                       systolic_dt_2 = col_datetime(format = "%Y-%m-%d %H:%M"),
                                       systolic_dt_3 = col_datetime(format = "%Y-%m-%d %H:%M"),
                                       systolic_dt_min = col_datetime(format = "%Y-%m-%d %H:%M"),
                                     )
                                     )

                                     
